remove mobile front for faster analysis

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -32,20 +32,28 @@ analysis:
       EOF
       )
       echo "Request Body: $REQUEST_BODY"
-      RESPONSE=$(curl --connect-timeout 0 --max-time 0 -s -w "\n%{http_code}" -X POST "$REMOTE_SERVER_API_ADDRESS/scanner/scan/analysis" \
+      ANALYSIS_RESPONSE=$(curl --connect-timeout 0 --max-time 0 -s -w "\n%{http_code}" -X POST "$REMOTE_SERVER_API_ADDRESS/scanner/scan/analysis" \
            -H "Content-Type: application/json" \
            -H "Authorization: $AUTH_TOKEN" \
            -d "$REQUEST_BODY")
-      HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
-      RESPONSE_BODY=$(echo "$RESPONSE" | sed '$ d')
-      echo "Curl Response: $RESPONSE_BODY"
-      if [ "$HTTP_STATUS" -ne 200 ]; then
-        echo "Request failed with status code $HTTP_STATUS"
+      ANALYSIS_HTTP_STATUS=$(echo "$ANALYSIS_RESPONSE" | tail -n1)
+      if [ "$ANALYSIS_HTTP_STATUS" -ne 200 ]; then
+        echo "Request failed with status code $ANALYSIS_HTTP_STATUS"
         ssh $REMOTE_USER@$REMOTE_SERVER "rm -rf $REMOTE_SERVER_TMP_DIR/$PROJECT_TEMP_NAME"
         exit 1
       fi
-      if [ "$RESPONSE_BODY" != "[]" ]; then
-        echo "Warning: Response is not an empty JSON array. Response: $RESPONSE_BODY"
+      ISSUES_RESPONSE=$(curl -s --connect-timeout 0 --max-time 0 -w "\n%{http_code}" -X GET "$REMOTE_SERVER_API_ADDRESS/scanner/issues/get-all-security-issues?name=$PROJECT_TEMP_NAME" \
+           -H "Content-Type: application/json" \
+           -H "Authorization: $AUTH_TOKEN")
+      ISSUES_HTTP_STATUS=$(echo "$ISSUES_RESPONSE" | tail -n1)
+      ISSUES_RESPONSE_BODY=$(echo "$ISSUES_RESPONSE" | sed '$ d')
+      if [ "$ISSUES_HTTP_STATUS" -ne 200 ]; then
+        echo "Request failed with status code $ISSUES_HTTP_STATUS"
+        ssh $REMOTE_USER@$REMOTE_SERVER "rm -rf $REMOTE_SERVER_TMP_DIR/$PROJECT_TEMP_NAME"
+        exit 1
+      fi
+      if [ "$ISSUES_RESPONSE_BODY" != "[]" ]; then
+        echo "Warning! Find security issues. List of issues: $ISSUES_RESPONSE_BODY"
         ssh $REMOTE_USER@$REMOTE_SERVER "rm -rf $REMOTE_SERVER_TMP_DIR/$PROJECT_TEMP_NAME"
         exit 2  # Custom exit code for warnings
       fi
