added analysis ci - github

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -82,4 +82,32 @@ jobs:
         run: |
           mkdir -p ~/.ssh
           ssh-keyscan -H ${{ secrets.REMOTE_SERVER }} >> ~/.ssh/known_hosts
+        env:
+          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
 
+      - name: Fetch security issues
+        run: |
+          ISSUES_RESPONSE=$(curl -s --connect-timeout 0 --max-time 0 -w "\n%{http_code}" -X GET "${{ secrets.REMOTE_SERVER_API_ADDRESS }}/scanner/issues/get-all-security-issues?name=$PROJECT_TEMP_NAME" \
+            -H "Content-Type: application/json" \
+            -H "Authorization: ${{ secrets.AUTH_TOKEN }}")
+          ISSUES_HTTP_STATUS=$(echo "$ISSUES_RESPONSE" | tail -n1)
+          ISSUES_RESPONSE_BODY=$(echo "$ISSUES_RESPONSE" | sed '$ d')
+          if [ "$ISSUES_HTTP_STATUS" -ne 200 ]; then
+            echo "Request failed with status code $ISSUES_HTTP_STATUS"
+            exit 1
+          fi
+          if [ "$ISSUES_RESPONSE_BODY" != "[]" ]; then
+            echo "Warning! Found security issues"
+            echo "$ISSUES_RESPONSE_BODY"
+            echo "$ISSUES_RESPONSE_BODY" > issues_list.json
+            echo "Issues saved to file issues_list.json"
+            exit 2
+        env:
+          REMOTE_SERVER_API_ADDRESS: ${{ secrets.REMOTE_SERVER_API_ADDRESS }}
+          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
+      - name: Upload issues list artifact
+        if: success() || failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: issues_list
+          path: issues_list.json
